apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources:
      limits: # Not ensured resources
        cpu: "1.5"
        memory: "128Mi"
      requests: # Ensured resources
        cpu: "0.3"
        memory: "64Mi"
    args:
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
